# Generated by Django 4.2.20 on 2025-05-14 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(help_text='Users this file is shared with', related_name='files_shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='study_groups.studygroup'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
