# Generated by Django 4.2.20 on 2025-04-03 01:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Unique identifier for login', max_length=255, unique=True)),
                ('email', models.EmailField(help_text='Valid .edu email address', max_length=254, unique=True, validators=[apps.users.models.validate_edu_email])),
                ('name', models.CharField(help_text='Display name for the user', max_length=255)),
                ('shared_files', models.ManyToManyField(help_text='Files this user has shared', related_name='shared_by_users', to='files.file')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
