# Generated by Django 5.2 on 2025-05-06 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direct_messages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directchat',
            name='participants',
            field=models.ManyToManyField(related_name='direct_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deletedchat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_by_users', to='direct_messages.directchat'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directchat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='direct_messages.directmessage'),
        ),
        migrations.AlterUniqueTogether(
            name='deletedchat',
            unique_together={('user', 'chat')},
        ),
    ]
