# Generated by Django 4.2.20 on 2025-04-10 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='3-50 character group name', max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('description', models.TextField(help_text='Detailed description of group purpose')),
                ('subject', models.CharField(max_length=100)),
                ('max_members', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_identifier', models.CharField(editable=False, help_text='Auto-generated unique group ID', max_length=50, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Study Group',
                'ordering': ['-created_at'],
            },
        ),
    ]
