# Generated by Django 5.2 on 2025-05-06 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='3-50 character group name', max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('description', models.TextField(help_text='Detailed description of group purpose')),
                ('subject', models.CharField(max_length=100)),
                ('max_members', models.IntegerField(default=5, help_text='Number of maximum members (2-10)', validators=[django.core.validators.MinValueValidator(2, message='Maximum members must be at least 2'), django.core.validators.MaxValueValidator(10, message='Maximum members cannot exceed 10')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_identifier', models.CharField(editable=False, help_text='Auto-generated unique group ID', max_length=50, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Study Group',
                'ordering': ['-created_at'],
            },
        ),
    ]
