# Generated by Django 4.2.20 on 2025-04-03 01:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='3-50 character group name', max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('description', models.TextField(help_text='Detailed description of group purpose')),
                ('unique_identifier', models.CharField(editable=False, help_text='Auto-generated unique group ID', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Group creation timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion timestamp', null=True)),
                ('members', models.ManyToManyField(help_text='All participants in the group', related_name='joined_groups', to='users.user')),
                ('owner', models.ForeignKey(help_text='Creator/admin of the group', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='users.user')),
            ],
            options={
                'verbose_name': 'Study Group',
            },
        ),
    ]
