# Generated by Django 4.2.20 on 2025-04-08 21:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study Group'},
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='owner',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studygroup',
            name='max_members',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(help_text='3-50 character group name', max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
